# Generated by Django 2.2.5 on 2021-07-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NUM_1', models.CharField(max_length=20)),
                ('FEEDER', models.CharField(max_length=20)),
                ('TYCOD', models.CharField(max_length=20)),
                ('OFF_DTS', models.DateTimeField()),
                ('EVENT_CREATION_TYPE', models.CharField(max_length=30)),
                ('SC', models.CharField(max_length=20)),
                ('XDTS', models.CharField(blank=True, max_length=20, null=True)),
                ('OTHER_EVENTS', models.IntegerField(blank=True, null=True)),
                ('ALARMS', models.IntegerField(blank=True, null=True)),
                ('EID', models.IntegerField(blank=True, null=True)),
                ('PRIORITY', models.CharField(max_length=30)),
                ('LOCATIONS', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'events',
                'db_table': 'events',
            },
        ),
    ]
